### ISSUE TITLE
C compiler fails to compile runtime.c during `raco pkg install`

### ISSUE THREAD

**Issue by nano-o** [Bogdanp/racket-wasm#2]
The error is:
`runtime.c:370:19: error: implicit conversion from 'long' to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Werror,-Wimplicit-const-int-float-conversion]`

**Comment by Bogdanp** [comment]
Thanks for the report! Please let me know if the change I just pushed fixes the problem for you (I wasn't able to replicate it locally).

Also, note that this project is likely severely bitrotted at this point 😅.

**Comment by nano-o** [comment]
Thanks, my C compiler does not complain anymore.
What do you think has bitrotted? Should I expect big surprises even if I stick to WASM 1.0?
I was hoping to experiment with symbolic execution of WASM by lifting your interpreter to a symbolic execution engine using Rosette.

**Comment by Bogdanp** [comment]
I was thinking of stuff like the runtime support for Wasm-compiled Go code, but it looks like that stuff's not even committed here so shouldn't be a problem. The interpreter should be fine.

**Comment by Bogdanp** [comment]
I'm going to go ahead and close this, but feel free to reopen if this is still a problem.
