### ISSUE TITLE
Any thoughts on support WASM extensions?

### ISSUE THREAD

**Issue by samdphillips** [Bogdanp/racket-wasm#4]
- Are there any thoughts on how to handle WASM extensions?
- If an extension is implemented should it be always on or behind some sort of "feature flag" mechanism?

**Comment by Bogdanp** [comment]
I'd love to support some of the extensions, though I don't think I'll have the time to work on any soon. I think in cases where an extension might change the behaviour or perf characteristics of compiled WASM, we'll have to make the extensions opt-in. But, I haven't been following closely enough so I don't know if there even are extensions like that. For example, I think the tail call extension just adds new call and return instructions to support tail calls.

**Comment by samdphillips** [comment]
Thanks for the reply.  I have been thinking about hacking on the vm a little and wanted to make sure I didn't do anything you may hate 😄
